### ISSUE TITLE
Difference between this fork and the the original code?

### ISSUE THREAD

**Issue by pke** [Telerik-Verified-Plugins/SQLite#1]
This master seems to be way behind the current original master. What's the current state of the plugin?

**Comment by EddyVerbruggen** [comment]
Fair point. We're definitely maintaining it by a.o. things keeping an eye out for updates on the upstream repository. Usually we look for new release tags since our last update.

The upstream has a lot of commits since our [forked release](https://github.com/litehelpers/Cordova-sqlite-storage/releases/tag/0.7.6), but it hasn't tagged (almost) any releases since then. The last one is from April, so it's hard to tell if the current upstream state is stable enough to update our fork.

That being said I'll keep this issue open as a reminder and will check back regularly to see if a stable release has been tagged over there.

**Comment by pke** [comment]
Ah ok. I was looking for a stable SQLite plugin. I'll try both and see which works best.
